[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.25"    # Solana version to use(applies to all Solana tools)

[features]
seeds = false
skip-lint = false

[programs.mainnet]
bridge = "9q7cek9TaaRvExbAfKdAgUTzu92RvNTzCxVutXV1nDRC"

[programs.devnet]
bridge = "9q7cek9TaaRvExbAfKdAgUTzu92RvNTzCxVutXV1nDRC"

[programs.localnet]
bridge = "9q7cek9TaaRvExbAfKdAgUTzu92RvNTzCxVutXV1nDRC"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://broken-twilight-paper.solana-devnet.quiknode.pro/e0bcf0275d294a569bd60a39c2a3f99d678b14d4"
wallet = "./cli/.config/secret.json"

[scripts]
test = "vitest --test-timeout=500000 2."

# use localnet for test
[test]
startup_wait = 50000000
shutdown_wait = 20000